In [1]:
from PIL import Image

In [2]:
image = Image.open("image.jpg") 

In [3]:
from PIL import ImageShow

In [4]:
ImageShow.show(image)

True

In [5]:
# Get image size (width, height) as a tuple
width, height = image.size

# Access other image properties
format = image.format  # Image format (e.g., JPEG, PNG)
mode = image.mode  # Color mode (e.g., RGB, grayscale)

print(f"Image resolution: {width}x{height} pixels")
print(f"Image format: {format}")
print(f"Image mode: {mode}")

Image resolution: 640x397 pixels
Image format: JPEG
Image mode: RGB


In [9]:
print(width)
print(height)

640
397


In [16]:
new_width = round(width/2)
new_height = round(height/2)
print(new_width)
print(type(new_width))
print(new_height)
print(type(new_height))

320
<class 'int'>
198
<class 'int'>


In [7]:
# Resize the image
#aspect ratio nich preserved
resized_image = image.resize((256, 256))  # Resize to 256x256 pixels
ImageShow.show(resized_image)

True

In [17]:
#esize with preserved aspect ration
resized_image_aspect_ratio = image.resize((new_width,new_height))
ImageShow.show(resized_image_aspect_ratio)

True

In [18]:
#save the resized image 
resized_image_aspect_ratio.save("image_resized.jpg")
print("The resized image has been saved")


The resized image has been saved


In [ ]:
# Convert to grayscale
grayscale_image = resized_image.convert('L')  # 'L' for grayscale mode

In [ ]:
# Save the manipulated image
grayscale_image.save("grayscale_image.jpg")

In [9]:
#rotating an image

# Open the image
#image = Image.open("image.jpg")

# Rotate the image by 45 degrees counter-clockwise
angle = 45
rotated_image = image.rotate(angle)

# Save the rotated image
#rotated_image.save("rotated_image.jpg")
#show
ImageShow.show(rotated_image)

True

In [25]:
#Watermark
from PIL import Image, ImageDraw, ImageFont

# Create an Image Object from an Image
im = Image.open('image.jpg')
width, height = im.size

draw = ImageDraw.Draw(im)
text = "dusarpa photo"

font = ImageFont.truetype('arial.ttf', 24)
textwidth = draw.textlength(text, font)  # Use textlength instead of textsize

# Calculate the x coordinate (text height calculation remains the same)
margin = 10
x = width - textwidth - margin
y = height - font.size  # Use font.size for text height

# Draw watermark in the bottom right corner
draw.text((x, y), text, font=font)
im.show()

# Save watermarked image
#im.save('images/watermark.jpg')


In [26]:
#creating numpy array from an image
#from PIL import Image
from numpy import array

#Open Image & create image object
img = Image.open('image.jpg')

#Show actual image
img.show()

#Convert an image to numpy array
img2arr = array(img)

#Print the array
print(img2arr)

#Convert numpy array back to image
#arr2im = Image.fromarray(img2arr)

#Display image
#arr2im.show()

#Save the image generated from an array
#arr2im.save("array2Image.jpg")

[[[191 192 212]
  [191 192 212]
  [191 192 212]
  ...
  [201 201 209]
  [198 198 206]
  [199 199 207]]

 [[189 190 210]
  [189 190 210]
  [189 190 208]
  ...
  [195 195 203]
  [196 196 204]
  [200 200 208]]

 [[188 189 207]
  [188 189 207]
  [188 189 207]
  ...
  [200 200 208]
  [200 200 208]
  [202 202 210]]

 ...

 [[108 112 147]
  [121 126 156]
  [125 132 158]
  ...
  [153 149 148]
  [155 151 150]
  [152 148 147]]

 [[ 76  80 115]
  [105 110 140]
  [129 135 161]
  ...
  [167 162 159]
  [166 161 158]
  [159 154 151]]

 [[ 68  71 106]
  [101 104 135]
  [125 131 157]
  ...
  [179 171 168]
  [173 165 162]
  [162 154 151]]]


In [31]:
img2arr.shape

(397, 640, 3)


** (gdk-pixbuf-thumbnailer:27219): WARNING **: 22:26:51.275: Could not thumbnail 'file:///tmp/.com.google.Chrome.BUs7IJ': Error interpreting JPEG image file (Improper call to JPEG library in state 205)
