In [2]:
import torch
import numpy as np

print('PyTorch version:', torch.__version__)

np.set_printoptions(precision=3)

PyTorch version: 1.12.1


In [3]:
a = [1, 2, 3]
b = np.array([4, 5, 6], dtype=np.int32)

t_a = torch.tensor(a)
t_b = torch.from_numpy(b)

print(t_a)
print(t_b)

tensor([1, 2, 3])
tensor([4, 5, 6], dtype=torch.int32)


In [4]:
torch.is_tensor(a), torch.is_tensor(t_a)

(False, True)

In [5]:
t_ones = torch.ones(2, 3)
print(t_ones)
t_ones.shape

tensor([[1., 1., 1.],
        [1., 1., 1.]])


torch.Size([2, 3])

In [6]:
rand_tensor = torch.rand(2,3)
print(rand_tensor)

tensor([[0.0511, 0.8145, 0.4993],
        [0.9303, 0.4407, 0.7106]])


In [ ]:
#Manipulating the data type and shape of a tensor

In [7]:
t_a_new = t_a.to(torch.int64)
print(t_a_new.dtype)

torch.int64


In [8]:
#transpose
t = torch.rand(3, 5)
print(t)
t_tr = torch.transpose(t, 0, 1)
print(t_tr)
print(t.shape, ' --> ', t_tr.shape)

tensor([[0.8067, 0.1062, 0.5504, 0.8128, 0.2222],
        [0.2544, 0.7881, 0.5593, 0.2769, 0.4275],
        [0.7788, 0.4905, 0.5884, 0.1796, 0.4833]])
tensor([[0.8067, 0.2544, 0.7788],
        [0.1062, 0.7881, 0.4905],
        [0.5504, 0.5593, 0.5884],
        [0.8128, 0.2769, 0.1796],
        [0.2222, 0.4275, 0.4833]])
torch.Size([3, 5])  -->  torch.Size([5, 3])


In [9]:
#reshape
t = torch.zeros(30)
print(t)
t_reshape = t.reshape(5, 6)
print(t_reshape)
print(t_reshape.shape)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
torch.Size([5, 6])


In [10]:
#squeeze
t = torch.zeros(1, 2, 1, 4, 1)
print(t)
t_sqz = torch.squeeze(t, 2)
print(t_sqz)
print(t.shape, ' --> ', t_sqz.shape)

tensor([[[[[0.],
           [0.],
           [0.],
           [0.]]],


         [[[0.],
           [0.],
           [0.],
           [0.]]]]])
tensor([[[[0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.]]]])
torch.Size([1, 2, 1, 4, 1])  -->  torch.Size([1, 2, 4, 1])


In [ ]:
#Applying mathematical operations to tensors

In [17]:
torch.manual_seed(1)

t1 = 2 * torch.rand(5, 2) - 1 
t2 = torch.normal(mean=0, std=1, size=(5, 2))
print(f"t1 = {t1}")
print(f"t2 = {t2}")

t1 = tensor([[ 0.5153, -0.4414],
        [-0.1939,  0.4694],
        [-0.9414,  0.5997],
        [-0.2057,  0.5087],
        [ 0.1390, -0.1224]])
t2 = tensor([[ 0.8590,  0.7056],
        [-0.3406, -1.2720],
        [-1.1948,  0.0250],
        [-0.7627,  1.3969],
        [-0.3245,  0.2879]])


In [12]:
#elementwise multiplication
t3 = torch.multiply(t1, t2)
print(t3)

tensor([[ 0.4426, -0.3114],
        [ 0.0660, -0.5970],
        [ 1.1249,  0.0150],
        [ 0.1569,  0.7107],
        [-0.0451, -0.0352]])


In [13]:
#mean through columns
t4 = torch.mean(t1, axis=0)
print(t4)

tensor([-0.1373,  0.2028])


In [19]:
#mean through rows
t4 = torch.mean(t1, axis=1)
print(t4)

tensor([ 0.0369,  0.1378, -0.1709,  0.1515,  0.0083])


In [21]:
#matrix multiplication
t5 = torch.matmul(t1, torch.transpose(t2, 0, 1))
print(t5)

tensor([[ 0.1312,  0.3860, -0.6267, -1.0096, -0.2943],
        [ 0.1647, -0.5310,  0.2434,  0.8035,  0.1980],
        [-0.3855, -0.4422,  1.1399,  1.5558,  0.4781],
        [ 0.1822, -0.5771,  0.2585,  0.8676,  0.2132],
        [ 0.0330,  0.1084, -0.1692, -0.2771, -0.0804]])


In [22]:
t6 = torch.matmul(torch.transpose(t1, 0, 1), t2)

print(t6)

tensor([[ 1.7453,  0.3392],
        [-1.6038, -0.2180]])


In [23]:
#L2 norm
norm_t1 = torch.linalg.norm(t1, ord=2, dim=1)
print(norm_t1)

tensor([0.6785, 0.5078, 1.1162, 0.5488, 0.1853])


In [24]:
np.sqrt(np.sum(np.square(t1.numpy()), axis=1))

array([0.678, 0.508, 1.116, 0.549, 0.185], dtype=float32)

In [ ]:
#Split, stack, and concatenate tensors

In [25]:
torch.manual_seed(1)
t = torch.rand(6)
print(t)

t_splits = torch.chunk(t, 3)
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293, 0.7999])


[array([0.758, 0.279], dtype=float32),
 array([0.403, 0.735], dtype=float32),
 array([0.029, 0.8  ], dtype=float32)]

In [28]:
torch.manual_seed(1)
t = torch.rand(5)

print(t)

t_splits = torch.split(t, split_size_or_sections=[4, 1])
 
[item.numpy() for item in t_splits]

tensor([0.7576, 0.2793, 0.4031, 0.7347, 0.0293])


[array([0.758, 0.279, 0.403, 0.735], dtype=float32),
 array([0.029], dtype=float32)]

In [31]:
A = torch.ones(3)
B = torch.zeros(2)
print(f"A = {A} and B = {B}")
C = torch.cat([A, B], axis=0)
print(C)

A = tensor([1., 1., 1.]) and B = tensor([0., 0.])
tensor([1., 1., 1., 0., 0.])


In [35]:
A = torch.ones(3)
B = torch.zeros(3)
print(f"A = {A} and B = {B}")
S = torch.stack([A, B], axis=1)
print(S)

A = tensor([1., 1., 1.]) and B = tensor([0., 0., 0.])
tensor([[1., 0.],
        [1., 0.],
        [1., 0.]])


In [ ]:
#Building input pipelines in PyTorch
#Creating a PyTorch dataloader from existing tensors